[2022-02-13 06:03:36,347] WARN Client session timed out, have not heard from server in 53308ms for session id 0x10004ff6c8f000d (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:36,391] WARN Client session timed out, have not heard from server in 52677ms for session id 0x10004ff6c8f000e (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:36,453] INFO Expiring session 0x10004ff6c8f000d, timeout of 18000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2022-02-13 06:03:36,405] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Disconnecting from node 0 due to request timeout. (org.apache.kafka.clients.NetworkClient)
[2022-02-13 06:03:36,597] INFO Expiring session 0x10004ff6c8f000e, timeout of 18000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2022-02-13 06:03:36,596] WARN Session 0x10004ff6c8f000d for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 53308ms for session id 0x10004ff6c8f000d
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
[2022-02-13 06:03:36,600] WARN Session 0x10004ff6c8f000e for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 52677ms for session id 0x10004ff6c8f000e
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
[2022-02-13 06:03:36,446] INFO [GroupCoordinator 0]: Member console-consumer-fe5aed57-f245-4046-b14b-13df9b94a0c7 in group console-consumer-21310 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2022-02-13 06:03:36,711] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Cancelled in-flight FETCH request with correlation id 34359 due to node 0 being disconnected (elapsed time since creation: 6475048ms, elapsed time since send: 6475048ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient)
[2022-02-13 06:03:36,373] INFO [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Disconnecting from node 1 due to request timeout. (org.apache.kafka.clients.NetworkClient)
[2022-02-13 06:03:36,822] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Client requested connection close from node 0 (org.apache.kafka.clients.NetworkClient)
[2022-02-13 06:03:36,867] INFO [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Cancelled in-flight FETCH request with correlation id 34360 due to node 1 being disconnected (elapsed time since creation: 6475319ms, elapsed time since send: 6475319ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient)
[2022-02-13 06:03:36,881] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-21310 in state PreparingRebalance with old generation 3 (__consumer_offsets-38) (reason: removing member console-consumer-fe5aed57-f245-4046-b14b-13df9b94a0c7 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2022-02-13 06:03:36,843] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=20403321, epoch=350) to node 0: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 0 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-13 06:03:36,942] INFO [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Client requested connection close from node 1 (org.apache.kafka.clients.NetworkClient)
[2022-02-13 06:03:37,417] WARN [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=1, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, removed=, replaced=, metadata=(sessionId=20403321, epoch=350), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 0 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-13 06:03:37,305] INFO [GroupCoordinator 0]: Group console-consumer-21310 with generation 4 is now empty (__consumer_offsets-38) (kafka.coordinator.group.GroupCoordinator)
[2022-02-13 06:03:37,500] INFO [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=1890218694, epoch=350) to node 1: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 1 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-13 06:03:37,710] WARN [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=0, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, removed=, replaced=, metadata=(sessionId=1890218694, epoch=350), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 1 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-13 06:03:37,745] INFO [GroupCoordinator 0]: Dynamic member with unknown member id joins group console-consumer-21310 in Empty state. Created a new member id console-consumer-06e0a6d8-61b3-482d-8c54-80698ae2f90e and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2022-02-13 06:03:37,890] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-21310 in state PreparingRebalance with old generation 4 (__consumer_offsets-38) (reason: Adding new member console-consumer-06e0a6d8-61b3-482d-8c54-80698ae2f90e with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2022-02-13 06:03:38,001] INFO [GroupCoordinator 0]: Stabilized group console-consumer-21310 generation 5 (__consumer_offsets-38) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2022-02-13 06:03:38,006] INFO [GroupCoordinator 0]: Assignment received from leader console-consumer-06e0a6d8-61b3-482d-8c54-80698ae2f90e for group console-consumer-21310 for generation 5. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2022-02-13 06:03:38,065] INFO Opening socket connection to server localhost/127.0.0.1:2181. (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,075] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,077] INFO Socket connection established, initiating session, client: /127.0.0.1:49790, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,081] INFO Invalid session 0x10004ff6c8f000e for client /127.0.0.1:49790, probably expired (org.apache.zookeeper.server.ZooKeeperServer)
[2022-02-13 06:03:38,082] WARN Unable to reconnect to ZooKeeper service, session 0x10004ff6c8f000e has expired (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,082] WARN Session 0x10004ff6c8f000e for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionExpiredException: Unable to reconnect to ZooKeeper service, session 0x10004ff6c8f000e has expired
	at org.apache.zookeeper.ClientCnxn$SendThread.onConnected(ClientCnxn.java:1434)
	at org.apache.zookeeper.ClientCnxnSocket.readConnectResult(ClientCnxnSocket.java:154)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:86)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-13 06:03:38,083] INFO EventThread shut down for session: 0x10004ff6c8f000e (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,084] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2022-02-13 06:03:38,088] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2022-02-13 06:03:38,089] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@6ebf0f36 (org.apache.zookeeper.ZooKeeper)
[2022-02-13 06:03:38,091] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2022-02-13 06:03:38,091] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,119] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,119] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,119] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:49791, server: localhost/0:0:0:0:0:0:0:1:2181 (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,240] INFO Opening socket connection to server localhost/127.0.0.1:2181. (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,369] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,371] INFO Socket connection established, initiating session, client: /127.0.0.1:49795, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,372] INFO Session establishment complete on server localhost/0:0:0:0:0:0:0:1:2181, session id = 0x10004ff6c8f000f, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,374] INFO Invalid session 0x10004ff6c8f000d for client /127.0.0.1:49795, probably expired (org.apache.zookeeper.server.ZooKeeperServer)
[2022-02-13 06:03:38,376] WARN Unable to reconnect to ZooKeeper service, session 0x10004ff6c8f000d has expired (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,376] WARN Session 0x10004ff6c8f000d for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionExpiredException: Unable to reconnect to ZooKeeper service, session 0x10004ff6c8f000d has expired
	at org.apache.zookeeper.ClientCnxn$SendThread.onConnected(ClientCnxn.java:1434)
	at org.apache.zookeeper.ClientCnxnSocket.readConnectResult(ClientCnxnSocket.java:154)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:86)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-13 06:03:38,376] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2022-02-13 06:03:38,376] INFO EventThread shut down for session: 0x10004ff6c8f000d (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,388] INFO Updated cache from existing FinalizedFeaturesAndEpoch(features=Features{}, epoch=0) to latest FinalizedFeaturesAndEpoch(features=Features{}, epoch=0). (kafka.server.FinalizedFeatureCache)
[2022-02-13 06:03:38,744] INFO Creating /brokers/ids/1 (is it secure? false) (kafka.zk.KafkaZkClient)
[2022-02-13 06:03:38,758] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2022-02-13 06:03:38,758] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@2e8e8225 (org.apache.zookeeper.ZooKeeper)
[2022-02-13 06:03:38,761] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2022-02-13 06:03:38,761] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,766] INFO Opening socket connection to server localhost/127.0.0.1:2181. (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,766] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:38,766] INFO Socket connection established, initiating session, client: /127.0.0.1:49800, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:39,136] INFO Stat of the created znode at /brokers/ids/1 is: 305,305,1644712418749,1644712418749,1,0,0,72063089122410511,202,0,305
 (kafka.zk.KafkaZkClient)
[2022-02-13 06:03:39,149] INFO Registered broker 1 at path /brokers/ids/1 with addresses: PLAINTEXT://localhost:9093, czxid (broker epoch): 305 (kafka.zk.KafkaZkClient)
[2022-02-13 06:03:39,393] INFO Session establishment complete on server localhost/127.0.0.1:2181, session id = 0x10004ff6c8f0010, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2022-02-13 06:03:39,788] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.zk.KafkaZkClient)
[2022-02-13 06:03:39,792] INFO Updated cache from existing FinalizedFeaturesAndEpoch(features=Features{}, epoch=0) to latest FinalizedFeaturesAndEpoch(features=Features{}, epoch=0). (kafka.server.FinalizedFeatureCache)
[2022-02-13 06:03:40,120] INFO Stat of the created znode at /brokers/ids/0 is: 308,308,1644712419901,1644712419901,1,0,0,72063089122410512,202,0,308
 (kafka.zk.KafkaZkClient)
[2022-02-13 06:03:40,124] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT://localhost:9092, czxid (broker epoch): 308 (kafka.zk.KafkaZkClient)
